#pragma once

#include "core/color.hpp"
#include "core/game.hpp"
#include "core/graphicsdevice.hpp"
#include "core/log.hpp"
#include "core/rectangle.hpp"
#include "core/resourcemanager.hpp"
#include "core/shader.hpp"
#include "core/spritebatch.hpp"
#include "core/texture2D.hpp"
#include "core/viewport.hpp"
#include "core/window.hpp"

#include "world/map.hpp"
#include "world/renderer.hpp"
#include "world/tile.hpp"
#include "world/tileset.hpp"
#include "world/tilesetinfo.hpp"
#include "world/maplayer.hpp"
#include "world/tilelayer.hpp"
#include "world/objectlayer.hpp"

#include "scene/scene.hpp"
#include "scene/entity.hpp"
#include "scene/observer.hpp"
#include "scene/components/childcomponent.hpp"
#include "scene/components/movecomponent.hpp"
#include "scene/components/positioncomponent.hpp"
#include "scene/components/tagcomponent.hpp"
#include "scene/components/cameracomponent.hpp"

#include "sprites/sprite.hpp"
#include "sprites/spritesheet.hpp"